### ISSUE TITLE
A few links

### ISSUE THREAD

**Issue by jf990** [Esri/esri.github.com#55]
With the new design we should add a link to [Open Source](https://www.esri.com/software/open/open-source) and a link to [esri github](https://github.com/Esri/).

**Comment by jgravois** [comment]
👍  i have a link to the first in the mission statement, it just needs to be more prominent.

the link in the footer should be updated (so that it doesn't just redirect back to esri.github.io) and a note should be added below the showcased cards saying something to the effect of 'browse all esri projects on github'...
